using System.Data.Entity;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.ModelConfiguration.Conventions;
using GeekBooks.MySQL_Identity;
using System.Collections.Generic;

namespace GeekBooks.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit https://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
        [Required(ErrorMessage = "First Name is Required")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last Name is Required")]
        public string LastName { get; set; }

        public virtual ICollection<Avatar> Avatar { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<CreditCard> CreditCards { get; set; }
        public virtual ICollection<BookRating> BookRatings { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("MyDbContextConnectionString", throwIfV1Schema: false)
        {
            Database.SetInitializer(new MySqlInitializer());
            
            Database.SetInitializer(new MyDbInitializer());
        }

        public DbSet<Avatar> Avatars { get; set; }
        public DbSet<Address> Addresses { get; set; }
        public DbSet<CreditCard> CreditCards { get; set; }
        public DbSet<BookAuthor> Authors { get; set; }
        public DbSet<Book> Books { get; set; }
        public DbSet<BookRating> BookRatings { get; set; }
        public DbSet<ShoppingCart> ShoppingCarts { get; set; }
        public DbSet<Genre> Genres { get; set; }

        public static ApplicationDbContext Create()
        {
            return new ApplicationDbContext();
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {            
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<ApplicationUser>().HasMany(x => x.Addresses).WithRequired().HasForeignKey(x => x.UID).WillCascadeOnDelete();
            modelBuilder.Entity<ApplicationUser>().HasMany(x => x.Avatar).WithRequired().HasForeignKey(x => x.UID).WillCascadeOnDelete();
            modelBuilder.Entity<ApplicationUser>().HasMany(x => x.CreditCards).WithRequired().HasForeignKey(x => x.UID).WillCascadeOnDelete();
            modelBuilder.Entity<ApplicationUser>().HasMany(x => x.BookRatings).WithOptional(y => y.User).WillCascadeOnDelete();
            modelBuilder.Entity<ApplicationUser>().HasMany(x => x.ShoppingCarts).WithOptional(y => y.User).WillCascadeOnDelete();
        }
    }

    public class MyDbInitializer : DropCreateDatabaseIfModelChanges<ApplicationDbContext>
    {
        protected override void Seed(ApplicationDbContext context)
        {
            //context.Genres.Add(new Genre { GenreID = 1, GenreTitle = "Science Fiction" });
            //context.Genres.Add(new Genre { GenreID = 2, GenreTitle = "Fantasy" });
            //context.Genres.Add(new Genre { GenreID = 3, GenreTitle = "Fiction" });
            //context.Genres.Add(new Genre { GenreID = 4, GenreTitle = "Mystery" });
            //context.Genres.Add(new Genre { GenreID = 5, GenreTitle = "Classic" });
            //context.Genres.Add(new Genre { GenreID = 6, GenreTitle = "Young Adult" });
            //context.Genres.Add(new Genre { GenreID = 7, GenreTitle = "Thriller" });
            //context.Genres.Add(new Genre { GenreID = 8, GenreTitle = "Adventure" });

            context.Authors.Add(new BookAuthor { AuthID = 1, AuthorName = "Robert Jackson Bennett", Blurb = "Robert Jackson Bennett is an American writer of speculative fiction. He is a two-time award winner of the Shirley Jackson Award for Best Novel, an Edgar Award winner for Best Paperback Original, and is also the 2010 recipient of the Sydney J Bounds Award for Best Newcomer, and a Philip K Dick Award Citation of Excellence." });
            context.Authors.Add(new BookAuthor { AuthID = 2, AuthorName = "Orson Scott Card", Blurb = "Card writes contemporary fantasy (Magic Street, Enchantment, Lost Boys), biblical novels (Stone Tables, Rachel and Leah), the American frontier fantasy series The Tales of Alvin Maker (beginning with Seventh Son), poetry (An Open Book), and many plays and scripts. Card was born in Washington and grew up in California, Arizona, and Utah. He served a mission for the LDS Church in Brazil in the early 1970s.Besides his writing, he teaches occasional classes and workshops and directs plays." });
            context.Authors.Add(new BookAuthor { AuthID = 3, AuthorName = "Timothy Zahn", Blurb = "Timothy Zahn attended Michigan State University, earning a Bachelor of Science degree in physics in 1973. He then moved to the University of Illinois at Urbana-Champaign and achieved an M.S. degree in physics in 1975. While he was pursuing a doctorate in physics, his adviser became ill and died. Zahn never completed the doctorate. In 1975 he had begun writing science fiction as a hobby, and he became a professional writer. " });
            context.Authors.Add(new BookAuthor { AuthID = 4, AuthorName = "Mike Carey", Blurb = "Mike Carey was born in Liverpool in 1959. He worked as a teacher for fifteen years, before starting to write comics. When he started to receive regular commissions from DC Comics, he gave up the day job." });
            context.Authors.Add(new BookAuthor { AuthID = 5, AuthorName = "Gregory Benford", Blurb = "American science fiction author and astrophyicist at University of California, Irvine. As a science fiction author, Benford is best known for the Galactic Center Saga novels, beginning with In the Ocean of Night (1977)." });
            context.Authors.Add(new BookAuthor { AuthID = 6, AuthorName = "Dan Moren", Blurb = "Novelist, freelance writer, and prolific podcaster. Dan Moren's been making up stories for as long as he can remember, and writing them down since he was old enough to hold a pencil. His first novel, the rollicking sci-fi adventure The Caledonian Gambit, is forthcoming from Talos Press." });
            context.Authors.Add(new BookAuthor { AuthID = 7, AuthorName = "George Orwell", Blurb = "Eric Arthur Blair, better known by his pen name George Orwell, was an English author and journalist. His work is marked by keen intelligence and wit, a profound awareness of social injustice, an intense opposition to totalitarianism, a passion for clarity in language, and a belief in democratic socialism."});
            context.Authors.Add(new BookAuthor { AuthID = 8, AuthorName = "Ray Bradbury", Blurb = "American novelist, short story writer, essayist, playwright, screenwriter and poet, was born August 22, 1920 in Waukegan, Illinois. He graduated from a Los Angeles high school in 1938. Although his formal education ended there, he became a 'student of life', selling newspapers on L.A. street corners from 1938 to 1942, spending his nights in the public library and his days at the typewriter. He became a full-time writer in 1943, and contributed numerous short stories to periodicals before publishing a collection of them, Dark Carnival, in 1947." });
            context.Authors.Add(new BookAuthor { AuthID = 9, AuthorName = "J.R.R. Tolkien", Blurb = "John Ronald Reuel Tolkien, CBE, was an English writer, poet, WWI veteran (a First Lieutenant in the Lancashire Fusiliers, British Army), philologist, and university professor, best known as the author of the high fantasy classic works The Hobbit and The Lord of the Rings ."});
            context.Authors.Add(new BookAuthor { AuthID = 10, AuthorName = "Rachel Aaron", Blurb = "Rachel Aaron is an American author of fantasy and science fiction.  Also writing under the pen name 'Rachel Back', Aaron is the author of the Heartstriker books and The Legend of Eli Monpress fantasy series." });
            context.Authors.Add(new BookAuthor { AuthID = 11, AuthorName = "J.K. Rowling", Blurb = "Although she writes under the pen name J.K. Rowling, pronounced like rolling, her name when her first Harry Potter book was published was simply Joanne Rowling. Anticipating that the target audience of young boys might not want to read a book written by a woman, her publishers demanded that she use two initials, rather than her full name. As she had no middle name, she chose K as the second initial of her pen name, from her paternal grandmother Kathleen Ada Bulgen Rowling." });
            context.Authors.Add(new BookAuthor { AuthID = 12, AuthorName = "Frank Herbert", Blurb = "Frank Herbert was a critically acclaimed and commercially successful American science fiction author.He is best known for the novel Dune and its five sequels.The Dune saga, set in the distant future and taking place over millennia, dealt with themes such as human survival and evolution, ecology, and the intersection of religion, politics, and power, and is widely considered to be among the classics in the field of science fiction." });
            context.Authors.Add(new BookAuthor { AuthID = 13, AuthorName = "H.G. Wells", Blurb = "In 1866, (Herbert George) H.G. Wells was born to a working class family in Kent, England. Young Wells received a spotty education, interrupted by several illnesses and family difficulties, and became a draper's apprentice as a teenager. Wells earned a government scholarship in 1884, to study biology under Thomas Henry Huxley at the Normal School of Science. After marrying his cousin, Isabel, Wells began to supplement his teaching salary with short stories and freelance articles, then books, including The Time Machine" });
            context.Authors.Add(new BookAuthor { AuthID = 14, AuthorName = "Mark Twain", Blurb = "Samuel Langhorne Clemens, better known by his pen name Mark Twain, was an American author and humorist. He is noted for his novels Adventures of Huckleberry Finn (1885), called 'the Great American Novel', and The Adventures of Tom Sawyer (1876). Twain grew up in Hannibal, Missouri, which would later provide the setting for Huckleberry Finn and Tom Sawyer." });
            context.Authors.Add(new BookAuthor { AuthID = 15, AuthorName = "Michael Crichton", Blurb = "Admired for his meticulous scientific research and fast-paced narrative. Crichton graduated summa cum laude and earned his MD from Harvard Medical School in 1969. His first novel, Odds On (1966), was written under the pseudonym John Lange and was followed by seven more Lange novels. He also wrote as Michael Douglas and Jeffery Hudson. His novel A Case of Need won the Edgar Award in 1969. Popular throughout the world, he has sold more than 200 million books and thirteen of his books have been made into films. Michael Crichton passed away from lymphoma in 2008.He was 66 years old." });
            context.Authors.Add(new BookAuthor { AuthID = 16, AuthorName = "Diana Gabaldon", Blurb = "Diana Jean Gabaldon Watkins grew up in Flagstaff, Arizona and is of Mexican-American and English descent. She has earned three degrees: a B.S. in Zoology, a M.S. in Marine Biology, and a Ph.D in Ecology. Her books merge multiple genres, featuring elements of historical fiction, romance, mystery, adventure and science fiction/fantasy. Recently a television adaptation of her Outlander series called 'Outlander' premiered on Starz in 2014." });
            context.Authors.Add(new BookAuthor { AuthID = 17, AuthorName = "Brandon Sanderson", Blurb = "Brandon Sanderson was born in 1975 in Lincoln, Nebraska. As a child Brandon enjoyed reading, but he lost interest in the types of titles often suggested to him, and by junior high he never cracked a book if he could help it. This changed when an eighth grade teacher gave him Dragonsbane by Barbara Hambly.\n\n The only author to make the short list for the David Gemmell Legend Award six times in four years, Brandon won that award in 2011 for The Way of Kings. The Emperor’s Soul won the 2013 Hugo Award for Best Novella. He has appeared on the New York Times Best-Seller List multiple times, with five novels hitting the #1 spot." });
            context.Authors.Add(new BookAuthor { AuthID = 18, AuthorName = "Paul Hoffman", Blurb = "Possibly the only novelist of his generation to be born by the light of a paraffin lamp, Paul Hoffman spent much of his childhood on airfields all around the world watching his father – a pioneer of sports parachuting and European Champion – jumping out of aeroplanes. After a long battle with the English educational system which involved avoiding school whenever possible he was offered a place to read English at New College, Oxford when no other university would interview him. After graduating he worked in over twenty different jobs, including boardman in a betting shop, messenger boy to a City merchant bank and teacher. He was also senior film censor at the British Board of Film Classification." });
            context.Authors.Add(new BookAuthor { AuthID = 19, AuthorName = "George R.R. Martin", Blurb = "George R.R. Martin was born September 20, 1948, in Bayonne, New Jersey. His father was Raymond Collins Martin, a longshoreman, and his mother was Margaret Brady Martin. He has two sisters, Darleen Martin Lapinski and Janet Martin Patten. Martin attended Mary Jane Donohoe School and Marist High School. He began writing very young, selling monster stories to other neighborhood children for pennies, dramatic readings included.Later he became a comic book fan and collector in high school, and began to write fiction for comic fanzines (amateur fan magazines). Martin's first professional sale was made in 1970 at age 21: 'The Hero,' sold to Galaxy, published in February, 1971 issue. Other sales followed. " });
            context.Authors.Add(new BookAuthor { AuthID = 20, AuthorName = "Philip Pullman", Blurb = "In 1946, acclaimed author Philip Pullman was born in Norwich, England, into a Protestant family. Although his beloved grandfather was an Anglican priest, Pullman became an atheist in his teenage years. He graduated from Exeter College in Oxford with a degree in English, and spent 23 years as a teacher while working on publishing 13 books and numerous short stories. Pullman has received many awards for his literature, including the prestigious Carnegie Medal for exceptional children’s literature in 1996, and the Carnegie of Carnegies in 2006." });
            context.Authors.Add(new BookAuthor { AuthID = 21, AuthorName = "Ken Kesey", Blurb = "American writer, who gained world fame with his novel One Flew Over the Cuckoo's Nest (1962, filmed 1975). In the 1960s, Kesey became a counterculture hero and a guru of psychedelic drugs with Timothy Leary. Kesey has been called the Pied Piper, who changed the beat generation into the hippie movement." });
            context.Authors.Add(new BookAuthor { AuthID = 22, AuthorName = "John Ajvide Lindqvist", Blurb = "John Ajvide Lindqvist (John Erik Ajvide Lindqvist) is a Swedish author who grew up in Blackeberg, the setting for Let the Right One In . Wanting to become something awful and fantastic, he first became a conjurer, and then was a stand-up comedian for twelve years. He has also written for Swedish television. His Let the Right One In was a bestseller in Sweden and was named Best Novel in Translation 2005 in Norway.He also is the author of Handling the Undead and Harbor." });
            context.Authors.Add(new BookAuthor { AuthID = 23, AuthorName = "David Sosnowski", Blurb = "David Sosnowski is the author of the novel Rapture and winner of the Thomas Wolfe Fiction Prize. He grew up in Detroit, Michigan, and has worked as a university writing instructor and a gag writer. His fiction has appeared in numerous magazines, including Passages North, River City, and Alaska Quarterly Review. Vamped is his second novel." });
            context.Authors.Add(new BookAuthor { AuthID = 24, AuthorName = "Paula Hawkins", Blurb = "Paula Hawkins is the author of the #1 New York Times bestseller The Girl on the Train, which was made into a major motion picture. Her new novel of psychological suspense is 'Into The Water'." });


            //seeding books
            context.Books.Add(new Book { PDate = new System.DateTime(2017, 5, 2), ASIN = "B01JWDWP7Q", BookID = 1, AuthorID = 1, CoverUrl = "http://prodimage.images-bn.com/pimages/9780553419740.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" } }, Price = (decimal)26.99, BookName = "City of Miracles", Publisher = "Crown/Archtype", Stock = 50, Synopsis = "Revenge. It’s something Sigrud je Harkvaldsson is very, very good at. Maybe the only thing. So when he learns that his oldest friend and ally former Prime Minister Shara Komayd, has been assassinated, he knows exactly what to do—and that no mortal force can stop him from meting out the suffering Shara’s killers deserve." });
            context.Books.Add(new Book { PDate = new System.DateTime(2017, 5, 2), ASIN = "B01M8G3KDW", BookID = 2, AuthorID = 3, CoverUrl = "http://prodimage.images-bn.com/pimages/9780765329660.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" } }, Price = (decimal)16.99, BookName = "Pawn", Publisher = "Tom Doherty Associates", Stock = 50, Synopsis = "Nicole Lee’s life is going nowhere. No family, no money, and stuck in a relationship with a thug named Bungie. But, after one of Bungie’s “deals” goes south, he and Nicole are whisked away by a mysterious moth-like humanoid to a strange ship called the Fyrantha." });
            context.Books.Add(new Book { PDate = new System.DateTime(2017, 5, 2), ASIN = "B01LL8BX9Q", BookID = 3, AuthorID = 4, CoverUrl = "http://prodimage.images-bn.com/pimages/9780316472203.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" } }, Price = (decimal)25.99, BookName = "The Boy on the Bridge", Publisher = "Orbit", Stock = 50, Synopsis = "Once upon a time, in a land blighted by terror, there was a very clever boy. The people thought the boy could save them, so they opened their gates and sent him out into the world. To where the monsters lived." });
            context.Books.Add(new Book { PDate = new System.DateTime(2017, 5, 9), ASIN = "B01HN13MRG", BookID = 4, AuthorID = 5, CoverUrl = "http://prodimage.images-bn.com/pimages/9781481487641.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" } }, Price = (decimal)17.49, BookName = "The Berlin Project", Publisher = "Saga Press", Stock = 50, Synopsis = "Karl Cohen, a chemist and mathematician who is part of The Manhattan Project team, has discovered an alternate solution for creating the uranium isotope..." });
            context.Books.Add(new Book { PDate = new System.DateTime(2017, 5, 23), ASIN = "B06XH5T4WG", BookID = 5, AuthorID = 6, CoverUrl = "http://prodimage.images-bn.com/pimages/9781940456843.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" } }, Price = (decimal)15.99, BookName = "The Caledonian Gambit", Publisher = "Talos", Stock = 50, Synopsis = "Simon Kovalic is the Commonwealth’s greatest spy, the sort of man who engineers planet-wide events in order to shift the balance of power. He identifies an opportunity on the planet of Caledonia..." });

            context.Books.Add(new Book { PDate = new System.DateTime(1983, 10, 17), ASIN = "B003JTHWKU", BookID = 6, AuthorID = 7, CoverUrl = "https://prodimage.images-bn.com/pimages/9780451524935_p0_v2_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" }, new Genre { GenreID = 2, GenreTitle = "Classic" }, new Genre { GenreID = 3, GenreTitle = "Dystopia" } }, Price = (decimal)8.99, BookName = "1984", Publisher = "Penguin Publising Group", Stock = 0, Synopsis = "Winston Smith toes the Party line, rewriting history to satisfy the demands of the Ministry of Truth. With each lie he writes, Winston grows to hate the Party that seeks power for its own sake and persecutes those who dare to commit thoughtcrimes. But as he starts to think for himself, Winston can’t escape the fact that Big Brother is always watching..." });
            context.Books.Add(new Book { PDate = new System.DateTime(2011, 11, 29), ASIN = "B0064CPN7I", BookID = 7, AuthorID = 8, CoverUrl = "https://prodimage.images-bn.com/pimages/9781451673265_p0_v7_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" }, new Genre { GenreID = 2, GenreTitle = "Classic" }, new Genre { GenreID = 3, GenreTitle = "Dystopia" } }, Price = (decimal)16.15, BookName = "Fahrenheit 451", Publisher = "Simon & Schuster", Stock = 50, Synopsis = "Guy Montag is a fireman. In his world, where television rules and literature is on the brink of extinction, firemen start fires rather than put them out. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden." });
            context.Books.Add(new Book { PDate = new System.DateTime(2015, 10, 20), ASIN = "B00V34YIOG", BookID = 8, AuthorID = 2, CoverUrl = "https://prodimage.images-bn.com/pimages/9780765365408_p0_v3_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" } }, Price = (decimal)25.99, BookName = "Gatefather", Publisher = "Tom Doherty Associates", Stock = 50, Synopsis = "Danny North is the first Gate Mage to be born on Earth in nearly 2000 years, or at least the first to survive to claim his power. Families of Westil in exile on Earth have had a treaty that required the death of any suspected Gate Mage. The wars between the Families had been terrible, until at last they realized it was their own survival in question." });
            context.Books.Add(new Book { PDate = new System.DateTime(2012, 2, 15), ASIN = "B0079KT81G", BookID = 9, AuthorID = 9, CoverUrl = "https://prodimage.images-bn.com/pimages/9780547928227_p0_v2_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Adventure" }, new Genre { GenreID = 3, GenreTitle = "Classic" } }, Price = (decimal)8.99, BookName = "The Hobbit", Publisher = "Houghton Mifflin Harcourt", Stock = 50, Synopsis = "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure." });
            context.Books.Add(new Book { PDate = new System.DateTime(2012, 6, 5), ASIN = "B005SCS70A", BookID = 10, AuthorID = 10, CoverUrl = "https://prodimage.images-bn.com/pimages/9780316198387_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Adventure" } }, Price = (decimal)25.99, BookName = "The Spirit war", Publisher = "Orbit", Stock = 50, Synopsis = "Eli Monpress is vain. He's cocky. And he's a thief. But he's a thief who has just seen his bounty topped and he's not happy about it.The bounty topper, as it turns out, is his best friend, bodyguard, and master swordsman, Josef.Who has been keeping secrets from Eli." });

            context.Books.Add(new Book { PDate = new System.DateTime(2012, 2, 15), ASIN = "B007978NPG", BookID = 11, AuthorID = 9, CoverUrl = "https://prodimage.images-bn.com/pimages/9780345339706_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Adventure" }, new Genre { GenreID = 3, GenreTitle = "Classic" } }, Price = (decimal)8.99, BookName = "The Fellowship of the Ring", Publisher = "Random House Publishing Group", Stock = 50, Synopsis = "The dark, fearsome Ringwraiths are searching for a Hobbit. Frodo Baggins knows that they are seeking him and the Ring he bears—the Ring of Power that will enable evil Sauron to destroy all that is good in Middle-earth. Now it is up to Frodo and his faithful servant, Sam, with a small band of companions, to carry the Ring to the one place it can be destroyed: Mount Doom, in the very center of Sauron’s realm." });
            context.Books.Add(new Book { PDate = new System.DateTime(2012, 2, 15), ASIN = "B007978PKY", BookID = 12, AuthorID = 9, CoverUrl = "https://prodimage.images-bn.com/pimages/9780345339713_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Adventure" }, new Genre { GenreID = 3, GenreTitle = "Classic" } }, Price = (decimal)18.99, BookName = "The Two Towers", Publisher = "Random House Publishing Group", Stock = 50, Synopsis = "The Fellowship is scattered. Some are bracing hopelessly for war against the ancient evil of Sauron. Some are contending with the treachery of the wizard Saruman. Only Frodo and Sam are left to take the accursed One Ring, ruler of all the Rings of Power, to be destroyed in Mordor, the dark realm where Sauron is supreme. Their guide is Gollum, deceitful and lust-filled, slave to the corruption of the Ring." });
            context.Books.Add(new Book { PDate = new System.DateTime(2012, 5, 15), ASIN = "B007978P18", BookID = 13, AuthorID = 9, CoverUrl = "https://prodimage.images-bn.com/pimages/9780345339737_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Adventure" }, new Genre { GenreID = 3, GenreTitle = "Classic" } }, Price = (decimal)18.99, BookName = "The Return of the King", Publisher = "Random House Publishing Group", Stock = 50, Synopsis = "While the evil might of the Dark Lord Sauron swarms out to conquer all Middle-earth, Frodo and Sam struggle deep into Mordor, seat of Sauron’s power. To defeat the Dark Lord, the One Ring, ruler of all the accursed Rings of Power, must be destroyed in the fires of Mount Doom. But the way is impossibly hard, and Frodo is weakening. Weighed down by the compulsion of the Ring, he begins finally to despair." });
            context.Books.Add(new Book { PDate = new System.DateTime(2009, 11, 30), ASIN = "B003H4I4JU", BookID = 14, AuthorID = 2, CoverUrl = "https://prodimage.images-bn.com/pimages/9781429963947_p0_v2_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" } }, Price = (decimal)7.99, BookName = "Speaker for the Dead", Publisher = "Tom Doherty Associates", Stock = 50, Synopsis = "In the aftermath of his terrible war, Ender Wiggin disappeared, and a powerful voice arose: The Speaker for the Dead, who told the true story of the Bugger War. Now, long years later, a second alien race has been discovered, but again the aliens' ways are strange and frightening...again, humans die. And it is only the Speaker for the Dead, who is also Ender Wiggin the Xenocide, who has the courage to confront the mystery...and the truth." });
            context.Books.Add(new Book { PDate = new System.DateTime(2009, 11, 30), ASIN = "B003H4I41S", BookID = 15, AuthorID = 2, CoverUrl = "https://prodimage.images-bn.com/pimages/9781429963961_p0_v4_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" } }, Price = (decimal)8.99, BookName = "Xenocide", Publisher = "Tom Doherty Associates", Stock = 50, Synopsis = "The war for survival of the planet Lusitania will be fought in the heart of a child named Gloriously Bright. On Lusitania, Ender found a world where humans and pequininos and the Hive Queen could all live together; where three very different intelligent species could find common ground at last. Or so he thought. Lusitania also harbors the descolada, a virus that kills all humans it infects, but which the pequininos require in order to become adults. The Starways Congress so fears the effects of the descolada, should it escape from Lusitania, that they have ordered the destruction of the entire planet, and all who live there.The Fleet is on its way, a second xenocide seems inevitable." });

            context.Books.Add(new Book { PDate = new System.DateTime(2009, 7, 1), ASIN = "B003K16PUU", BookID = 16, AuthorID = 7, CoverUrl = "https://prodimage.images-bn.com/pimages/9780451526342_p0_v2_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fiction" }, new Genre { GenreID = 2, GenreTitle = "Classic" }, new Genre { GenreID = 3, GenreTitle = "Dystopia" } }, Price = (decimal)8.99, BookName = "Animal Farm", Publisher = "Penguin Publising Group", Stock = 0, Synopsis = "A farm is taken over by its overworked, mistreated animals. With flaming idealism and stirring slogans, they set out to create a paradise of progress, justice, and equality. Thus the stage is set for one of the most telling satiric fables ever penned—a razor-edged fairy tale for grown-ups that records the evolution from revolution against tyranny to a totalitarianism just as terrible." });
            context.Books.Add(new Book { PDate = new System.DateTime(2012, 11, 20), ASIN = "B007BGQ4P6", BookID = 17, AuthorID = 10, CoverUrl = "https://prodimage.images-bn.com/pimages/9780316198363_p0_v2_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Adventure" } }, Price = (decimal)25.99, BookName = "Sprit's End", Publisher = "Orbit", Stock = 50, Synopsis = "First rule of thievery: don't be a hero. When Eli broke the rules and saved the Council Kingdoms, he thought he knew the price, but resuming his place as the Shepherdess's favorite isn't as simple as bowing his head. Now that she has her darling back, Benehime is setting in motion a plan that could destroy everything she was created to protect, and even Eli's charm might not be enough to stop her. " });
            context.Books.Add(new Book { PDate = new System.DateTime(2012, 2, 24), ASIN = "B0058ECNXU", BookID = 18, AuthorID = 10, CoverUrl = "https://prodimage.images-bn.com/pimages/9780316193573_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Adventure" } }, Price = (decimal)25.99, BookName = "The Legend of Eli Monpress", Publisher = "Orbit", Stock = 50, Synopsis = "Eli Monpress is talented. He's charming. And he's a thief. But not just any thief.He's the greatest thief of the age - and he's also a wizard.And with the help of his partners - a swordsman with the most powerful magic sword in the world but no magical ability of his own, and a demonseed who can step through shadows and punch through walls - he's going to put his plan into effect. The first step is to increase the size of the bounty on his head, so he'll need to steal some big things. But he'll start small for now.He'll just steal something that no one will miss - at least for a while. Like a king." });

            context.Books.Add(new Book { PDate = new System.DateTime(1997, 6, 26), ASIN = "B0192CTMYG", BookID = 19, AuthorID = 11, CoverUrl = "https://prodimage.images-bn.com/pimages/9780590353427_p0_v2_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Young Adult" }, new Genre { GenreID = 3, GenreTitle = "Adventure" } }, Price = (decimal)7.08, BookName = "Harry Potter and The Sorcerer's Stone", Publisher = "Scholastic Inc.", Stock = 50, Synopsis = "Harry Potter has never been the star of a Quidditch team, scoring points while riding a broom far above the ground. He knows no spells, has never helped to hatch a dragon, and has never worn a cloak of invisibility. All he knows is a miserable life with the Dursleys, his horrible aunt and uncle, and their abominable son, Dudley - a great big swollen spoiled bully.Harry's room is a tiny closet at the foot of the stairs, and he hasn't had a birthday party in eleven years. But all that is about to change when a mysterious letter arrives by owl messenger: a letter with an invitation to an incredible place that Harry - and anyone who reads about him - will find unforgettable." });
            context.Books.Add(new Book { PDate = new System.DateTime(1999, 6, 2), ASIN = "B0192CTMW8", BookID = 20, AuthorID = 11, CoverUrl = "https://prodimage.images-bn.com/pimages/9780439064873_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Young Adult" }, new Genre { GenreID = 3, GenreTitle = "Adventure" } }, Price = (decimal)25.99, BookName = "Harry Poter and the Chamber of Secrets", Publisher = "Scholastic Inc.", Stock = 50, Synopsis = "The Dursleys were so mean and hideous that summer that all Harry Potter wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he's packing his bags, Harry receives a warning from a strange, impish creature named Dobby who says that if Harry Potter returns to Hogwarts, disaster will strike. And strike it does.For in Harry's second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor, Gilderoy Lockheart, a spirit named Moaning Myrtle who haunts the girls' bathroom, and the unwanted attentions of Ron Weasley's younger sister, Ginny." });
            context.Books.Add(new Book { PDate = new System.DateTime(1999, 7, 8), ASIN = "B0192CTMX2", BookID = 21, AuthorID = 11, CoverUrl = "https://prodimage.images-bn.com/pimages/9780439136365_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Young Adult" }, new Genre { GenreID = 3, GenreTitle = "Adventure" } }, Price = (decimal)25.99, BookName = "Harry Potter and the Prisoner of Azkaban", Publisher = "Scholastic Inc.", Stock = 50, Synopsis = "For Twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort. Now he has escaped, leaving only two clues as to where he might be headed: Harry Potter's defeat of You-Know-Who was Black's downfall as well. And the Azkaban guards heard Black muttering in his sleep, 'He's at Hogwarts ... he's at Hogwarts.' Harry Potter isn't safe, not even within the walls of his magical school, surrounded by his friends. Because on top of it all, there may well be a traitor in their midst." });
            context.Books.Add(new Book { PDate = new System.DateTime(2002, 9, 28), ASIN = "B0192CTMUU", BookID = 22, AuthorID = 11, CoverUrl = "https://prodimage.images-bn.com/pimages/9780439139601_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Young Adult" }, new Genre { GenreID = 3, GenreTitle = "Adventure" } }, Price = (decimal)25.99, BookName = "Harry Potter and the Goblet of Fire", Publisher = "Scholastic Inc.", Stock = 50, Synopsis = "Harry Potter is midway through his training as a wizard and his coming of age. Harry wants to get away from the pernicious Dursleys and go to the International Quidditch Cup. He wants to find out about the mysterious event that's supposed to take place at Hogwarts this year, an event involving two other rival schools of magic, and a competition that hasn't happened for a hundred years. He wants to be a normal, fourteen-year-old wizard. But unfortunately for Harry Potter, he's not normal - even by wizarding standards. And in his case, different can be deadly." });
            context.Books.Add(new Book { PDate = new System.DateTime(2004, 8, 10), ASIN = "B0192CTMXM", BookID = 23, AuthorID = 11, CoverUrl = "https://prodimage.images-bn.com/pimages/9780439358071_p0_v4_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Young Adult" }, new Genre { GenreID = 3, GenreTitle = "Adventure" } }, Price = (decimal)25.99, BookName = "Harry Potter and the Oder of the Pheonix", Publisher = "Scholastic Inc.", Stock = 50, Synopsis = "In his fifth year at Hogwart's, Harry faces challenges at every turn, from the dark threat of He-Who-Must-Not-Be- Named and the unreliability of the government of the magical world to the rise of Ron Weasley as the keeper of the Gryffindor Quidditch Team. Along the way he learns about the strength of his friends, the fierceness of his enemies, and the meaning of sacrifice." });
            context.Books.Add(new Book { PDate = new System.DateTime(2006, 9, 16), ASIN = "B0192CTMWI", BookID = 24, AuthorID = 11, CoverUrl = "https://prodimage.images-bn.com/pimages/9780439785969_p0_v3_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Young Adult" }, new Genre { GenreID = 3, GenreTitle = "Adventure" } }, Price = (decimal)25.99, BookName = "Harry Potter and the Half-Blood Prince", Publisher = "Scholastic Inc.", Stock = 50, Synopsis = "The war against Voldemort is not going well; even Muggle governments are noticing. Ron scans the obituary pages of the Daily Prophet, looking for familiar names. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses. And yet...As in all wars, life goes on.Sixth - year students learn to Apparate-- and lose a few eyebrows in the process.The Weasley twins expand their business.Teenagers flirt and fight and fall in love.Classes are never straightforward, though Harry receives some extraordinary help from the mysterious Half - Blood Prince." });
            context.Books.Add(new Book { PDate = new System.DateTime(2007, 7, 21), ASIN = "B0192CTMWS", BookID = 25, AuthorID = 11, CoverUrl = "https://prodimage.images-bn.com/pimages/9780545139700_p0_v4_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Young Adult" }, new Genre { GenreID = 3, GenreTitle = "Adventure" } }, Price = (decimal)25.99, BookName = "Harry Potter and the Deathly Hallows", Publisher = "Scholastic Inc.", Stock = 50, Synopsis = "It all comes down to this - a final faceoff between good and evil. You plan to pull out all the stops, but every time you solve one mystery, three more evolve. Do you stay the course you started, despite your lack of progress? Do you detour and follow a new lead that may not help? Do you listen to your instincts, or your friends? Lord Voldemort is preparing for battle and so must Harry.With Ron and Hermione at his side, he's trying to hunt down Voldemort's Horcruxes, escape danger at every turn, and find a way to defeat evil once and for all.How does it all end ? Find out in Harry Potter and the Deathly Hallows." });

            context.Books.Add(new Book { PDate = new System.DateTime(2006, 2, 28), ASIN = "B01N6AY7VM", BookID = 26, AuthorID = 14, CoverUrl = "https://prodimage.images-bn.com/pimages/9780143039563_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fiction" }, new Genre { GenreID = 2, GenreTitle = "Adventure" }, new Genre { GenreID = 3, GenreTitle = "Classic" } }, Price = (decimal)8.99, BookName = "The Adventures of Tom Sawyer", Publisher = "Penguin Classics", Stock = 50, Synopsis = "From the famous episodes of the whitewashed fence and the ordeal in the cave to the trial of Injun Joe, The Adventures of Tom Sawyer is redolent of life in the Mississippi River towns in which Twain spent his own youth. A sombre undercurrent flows through the high humour and unabashed nostalgia of the novel, however, for beneath the innocence of childhood lie the inequities of adult reality—base emotions and superstitions, murder and revenge, starvation and slavery." });
            context.Books.Add(new Book { PDate = new System.DateTime(2002, 12, 31), ASIN = "B0716NJTPQ", BookID = 27, AuthorID = 14, CoverUrl = "https://prodimage.images-bn.com/pimages/9780141439648_p0_v2_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fiction" }, new Genre { GenreID = 2, GenreTitle = "Adventure" }, new Genre { GenreID = 3, GenreTitle = "Classic" } }, Price = (decimal)8.99, BookName = "The Adventures of Huckleberry Finn", Publisher = "Penguin Classics", Stock = 50, Synopsis = "Mark Twain's story of a boy's journey down the Mississippi on a raft conveyed the voice and experience of the American frontier as no other work had done before. When Huck escapes from his drunken, abusive 'Pap' and the 'sivilizing' Widow Douglas with runaway slave Jim, he embarks on a series of adventures that draw him to feuding families and the trickery of the unscrupulous 'Duke' and 'Dauphin'. Beneath the exploits, however, are more serious undercurrents - of slavery, adult control and, above all, of Huck's struggle between his instinctive goodness and the corrupt values of society which threaten his deep and enduring friendship with Jim." });
            context.Books.Add(new Book { PDate = new System.DateTime(1965, 12, 1), ASIN = "B00B7NPRY8", BookID = 28, AuthorID = 12, CoverUrl = "https://prodimage.images-bn.com/pimages/9781410477736_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" }, new Genre { GenreID = 2, GenreTitle = "Politics" }, new Genre { GenreID = 2, GenreTitle = "Classic" } }, Price = (decimal)14.49, BookName = "Dune", Publisher = "Gale Group", Stock = 50, Synopsis = "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, who would become the mysterious man known as Maud'dib. He would avenge the traitorous plot against his noble family--and would bring to fruition humankind's most ancient and unattainable dream. A stunning blend of adventure and mysticism, environmentalism and politics, Dune won the first Nebula Award, shared the Hugo Award, and formed the basis of what is undoubtedly the grandest epic in science fiction." });
            context.Books.Add(new Book { PDate = new System.DateTime(2002, 3, 12), ASIN = "B01MR9V9CT", BookID = 29, AuthorID = 13, CoverUrl = "https://prodimage.barnesandnoble.com/pimages/9781365707988_p0_v1_s466x700.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" }, new Genre { GenreID = 2, GenreTitle = "Thriller" }, new Genre { GenreID = 3, GenreTitle = "Classic" } }, Price = (decimal)9.99, BookName = "The War of the Worlds", Publisher = "Dover Publications", Stock = 50, Synopsis = "“No one would have believed in the last years of the nineteenth century that this world was being watched keenly and closely by intelligences greater than man’s and yet as mortal as his own.” Thus begins one of the most terrifying and morally prescient science fiction novels ever penned. Beginning with a series of strange flashes in the distant night sky, the Martian attack initially causes little concern on Earth. Then the destruction erupts—ten massive aliens roam England and destroy with heat rays everything in their path. Very soon mankind finds itself on the brink of extinction. Wells raises questions of mortality, man’s place in nature, and the evil lurking in the technological future" });
            context.Books.Add(new Book { PDate = new System.DateTime(1994, 7, 15), ASIN = "B003G4W49C", BookID = 30, AuthorID = 2, CoverUrl = "https://prodimage.barnesandnoble.com/pimages/9780613824224_p0_v1_s409x600.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" }, new Genre { GenreID = 2, GenreTitle = "Young Adult" } }, Price = (decimal)7.99, BookName = "Ender's Game", Publisher = "Tom Doherty Associates", Stock = 50, Synopsis = " Ender's parents have received a special dispensation to have a third child in spite of strict population control laws. His brilliant older siblings, Peter and Valentine, have each showed great promise, but each falls just short of having 'the right stuff'. The International Fleet (I.F.) believes that Ender may be the commander they need to lead great armies against invasion by alien 'buggers'. When Ender does exhibit the desired combination of compassion and cruelty, the I.F. takes him to the distant Battle School, where brilliant children are trained in military strategy and tactics." });
            context.Books.Add(new Book { PDate = new System.DateTime(2000, 12, 15), ASIN = "B003GWX8SK", BookID = 31, AuthorID = 2, CoverUrl = "https://prodimage.images-bn.com/pimages/9780765374714_p0_v4_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" }, new Genre { GenreID = 2, GenreTitle = "Young Adult" } }, Price = (decimal)9.99, BookName = "Ender's Shadow", Publisher = "Tom Doherty Associates", Stock = 50, Synopsis = "Bean's past was a battle just to survive. He first appeared on the streets of Rotterdam, a tiny child with a mind leagues beyond anyone else's. He knew he could not survive through strength; he used his tactical genius to gain acceptance into a children's gang, and then to help make that gang a template for success for all the others. He civilized them, and lived to grow older. Bean's desperate struggle to live, and his success, brought him to the attention of the Battle School's recruiters, those people scouring the planet for leaders, tacticians, and generals to save Earth from the threat of alien invasion.Bean was sent into orbit, to the Battle School.And there he met Ender...." });

            context.Books.Add(new Book { PDate = new System.DateTime(2017, 5, 23), ASIN = "B01JK5SU2U", BookID = 32, AuthorID = 15, CoverUrl = "https://prodimage.images-bn.com/pimages/9780062473356_p0_v2_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" }, new Genre { GenreID = 2, GenreTitle = "Fiction" } }, Price = (decimal)19.99, BookName = "Dragon Teeth", Publisher = "HarperCollins Publishers", Stock = 50, Synopsis = "The year is 1876. Warring Indian tribes still populate America’s western territories, even as lawless gold-rush towns begin to mark the landscape, and two monomaniacal paleontologists pillage the Wild West, hunting for dinosaur fossils while surveilling, deceiving, and sabotaging each other. Into this treacherous territory plunges William Johnson, a student who has joined world - renowned paleontologist Othniel Charles Marsh on his latest expedition.But when Marsh becomes convinced that William is spying for his nemesis, Edwin Drinker Cope, he abandons him in Cheyenne, Wyoming, a locus of crime and vice. William joins forces with Cope and soon stumbles upon a discovery of historic proportions.With this extraordinary treasure, however, comes exceptional danger, and Johnson’s newfound resilience will be sorely tested…" });
            context.Books.Add(new Book { PDate = new System.DateTime(2017, 6, 27), ASIN = "B01N54W5HD", BookID = 33, AuthorID = 16, CoverUrl = "https://prodimage.images-bn.com/pimages/9780399593420_p0_v3_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" }, new Genre { GenreID = 2, GenreTitle = "Romance" } }, Price = (decimal)25.99, BookName = "Seven Stones to Stand or Fall", Publisher = "Random House", Stock = 50, Synopsis = "“The Custom of the Army” begins with Lord John Grey being shocked by an electric eel and ends at the Battle of Quebec. Then comes “The Space Between,” where it is revealed that the Comte St. Germain is not dead, Master Raymond appears, and a widowed young wine dealer escorts a would-be novice to a convent in Paris. In “A Plague of Zombies,” Lord John unexpectedly becomes military governor of Jamaica when the original governor is gnawed by what probably wasn’t a giant rat. “A Leaf on the Wind of All Hallows” is the moving story of Roger MacKenzie’s parents during World War II. In “Virgins,” Jamie Fraser, aged nineteen, and Ian Murray, aged twenty, become mercenaries in France, no matter that neither has yet bedded a lass or killed a man. But they’re trying. . . . “A Fugitive Green” is the story of Lord John’s elder brother, Hal, and a seventeen-year-old rare book dealer with a sideline in theft, forgery, and blackmail. And finally, in “Besieged,” Lord John learns that his mother is in Havana—and that the British Navy is on their way to lay siege to the city." });
            context.Books.Add(new Book { PDate = new System.DateTime(2007, 4, 1), ASIN = "B003G93YLY", BookID = 34, AuthorID = 17, CoverUrl = "https://prodimage.images-bn.com/pimages/9780765350374_p0_v2_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Romance" }, new Genre { GenreID = 3, GenreTitle = "Adventure" } }, Price = (decimal)11.99, BookName = "Elantris", Publisher = "Tor", Stock = 50, Synopsis = "Elantris was the capital of Arelon: gigantic, beautiful, literally radiant, filled with benevolent beings who used their powerful magical abilities for the benefit of all. Yet each of these demigods was once an ordinary person until touched by the mysterious transforming power of the Shaod. Ten years ago, without warning, the magic failed. Elantrians became wizened, leper-like, powerless creatures, and Elantris itself dark, filthy, and crumbling. Arelon's new capital, Kae, crouches in the shadow of Elantris. Princess Sarene of Teod arrives for a marriage of state with Crown Prince Raoden, hoping -- based on their correspondence -- to also find love. She finds instead that Raoden has died and she is considered his widow. But Sarene does not suspect the truth about Prince Raoden. Stricken by the same curse that ruined Elantris, Raoden was secretly exiled by his father to the dark city.His struggle to help the wretches trapped there begins a series of events that will bring hope to Arelon, and perhaps reveal the secret of Elantris itself." });
            context.Books.Add(new Book { PDate = new System.DateTime(2010, 1, 7), ASIN = "B003NX75D6", BookID = 35, AuthorID = 18, CoverUrl = "https://prodimage.images-bn.com/pimages/9780525951315_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Thriller" } }, Price = (decimal)7.99, BookName = "The Left Hand of God", Publisher = "Penguin Group", Stock = 50, Synopsis = "The Sanctuary of the Redeemers is a vast and desolate place—a place without joy or hope. Most of its occupants were taken there as boys and for years have endured the brutal regime of the Lord Redeemers whose cruelty and violence have one singular purpose—to serve in the name of the One True Faith. In one of the Sanctuary’s vast and twisting maze of corridors stands a boy.He is perhaps fourteen or fifteen years old—he is not sure and neither is anyone else. He has long - forgotten his real name, but now they call him Thomas Cale.He is strange and secretive, witty and charming, violent and profoundly bloody - minded.He is so used to the cruelty that he seems immune, but soon he will open the wrong door at the wrong time and witness an act so terrible that he will have to leave this place, or die" });
            context.Books.Add(new Book { PDate = new System.DateTime(1963, 2, 1), ASIN = "B000SWV680", BookID = 36, AuthorID = 21, CoverUrl = "https://prodimage.images-bn.com/pimages/9780812416374_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fiction" }, new Genre { GenreID = 2, GenreTitle = "Classic" }, new Genre { GenreID = 3, GenreTitle = "Psychology" } }, Price = (decimal)9.99, BookName = "One Flew Over the Cuckoo's Nest", Publisher = "Penguin Classics", Stock = 50, Synopsis = "In this classic of the 1960s, Ken Kesey's hero is Randle Patrick McMurphy, a boisterous, brawling, fun-loving rebel who swaggers into the world of a mental hospital and takes over. A lusty, life-affirming fighter, McMurphy rallies the other patients around him by challenging the dictatorship of Nurse Ratched. He promotes gambling in the ward, smuggles in wine and women, and openly defies the rules at every turn. But this defiance, which starts as a sport, soon develops into a grim struggle, an all-out war between two relentless opponents: Nurse Ratched, back by the full power of authority, and McMurphy, who has only his own indomitable will." });

            context.Books.Add(new Book { PDate = new System.DateTime(1996, 8, 6), ASIN = "B000QCS8TW", BookID = 37, AuthorID = 19, CoverUrl = "https://prodimage.images-bn.com/pimages/9780553103540_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Thriller" }, new Genre { GenreID = 3, GenreTitle = "Politics" } }, Price = (decimal)8.99, BookName = "A Game of Thrones", Publisher = "Random House", Stock = 50, Synopsis = "Summers span decades. Winter can last a lifetime. And the struggle for the Iron Throne has begun. As Warden of the north, Lord Eddard Stark counts it a curse when King Robert bestows on him the office of the Hand.His honour weighs him down at court where a true man does what he will, not what he must … and a dead enemy is a thing of beauty. The old gods have no power in the south, Stark’s family is split and there is treachery at court.Worse, the vengeance - mad heir of the deposed Dragon King has grown to maturity in exile in the Free Cities.He claims the Iron Throne." });
            context.Books.Add(new Book { PDate = new System.DateTime(1998, 11, 16), ASIN = "B000FC1HBY", BookID = 38, AuthorID = 19, CoverUrl = "https://prodimage.images-bn.com/pimages/9780007459452_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Thriller" }, new Genre { GenreID = 3, GenreTitle = "Politics" } }, Price = (decimal)8.99, BookName = "A Clash of Kings", Publisher = "Random House", Stock = 50, Synopsis = "Time is out of joint. The summer of peace and plenty, ten years long, is drawing to a close, and the harsh, chill winter approaches like an angry beast. Two great leaders—Lord Eddard Stark and Robert Baratheon—who held sway over an age of enforced peace are dead...victims of royal treachery. Now, from the ancient citadel of Dragonstone to the forbidding shores of Winterfell, chaos reigns, as pretenders to the Iron Throne of the Seven Kingdoms prepare to stake their claims through tempest, turmoil, and war." });
            context.Books.Add(new Book { PDate = new System.DateTime(2000, 8, 8), ASIN = "B000FBFN1U", BookID = 39, AuthorID = 19, CoverUrl = "https://prodimage.barnesandnoble.com/pimages/9780007459469_p0_v1_s389x600.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Thriller" }, new Genre { GenreID = 3, GenreTitle = "Politics" } }, Price = (decimal)8.99, BookName = "A Storm of Swords", Publisher = "Random House", Stock = 50, Synopsis = "Of the five contenders for power, one is dead, another in disfavor, and still the wars rage as alliances are made and broken. Joffrey sits on the Iron Throne, the uneasy ruler of the Seven Kingdoms. His most bitter rival, Lord Stannis, stands defeated and disgraced, victim of the sorceress who holds him in her thrall. Young Robb still rules the North from the fortress of Riverrun. Meanwhile, making her way across a blood-drenched continent is the exiled queen, Daenerys, mistress of the only three dragons still left in the world. And as opposing forces manoeuver for the final showdown, an army of barbaric wildlings arrives from the outermost limits of civilization, accompanied by a horde of mythical Others—a supernatural army of the living dead whose animated corpses are unstoppable." });
            context.Books.Add(new Book { PDate = new System.DateTime(2005, 10, 17), ASIN = "B000FCKGPC", BookID = 40, AuthorID = 19, CoverUrl = "https://prodimage.barnesandnoble.com/pimages/9780007459476_p0_v1_s401x600.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Thriller" }, new Genre { GenreID = 3, GenreTitle = "Politics" } }, Price = (decimal)8.99, BookName = "A Feast for Crows", Publisher = "Random House", Stock = 50, Synopsis = "After centuries of bitter strife, the seven powers dividing the land have beaten one another into an uneasy truce. But it's not long before the survivors, outlaws, renegades, and carrion eaters of the Seven Kingdoms gather. Now, as the human crows assemble over a banquet of ashes, daring new plots and dangerous new alliances are formed while surprising faces—some familiar, others only just appearing—emerge from an ominous twilight of past struggles and chaos to take up the challenges of the terrible times ahead. Nobles and commoners, soldiers and sorcerers, assassins and sages, are coming together to stake their fortunes...and their lives. For at a feast for crows, many are the guests—but only a few are the survivors." });
            context.Books.Add(new Book { PDate = new System.DateTime(2011, 7, 12), ASIN = "B003YL4LYI", BookID = 41, AuthorID = 19, CoverUrl = "https://prodimage.images-bn.com/pimages/9780553801477_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Thriller" }, new Genre { GenreID = 3, GenreTitle = "Politics" } }, Price = (decimal)22.99, BookName = "A Dance with Dragons", Publisher = "Random House", Stock = 50, Synopsis = "In the aftermath of a colossal battle, the future of the Seven Kingdoms hangs in the balance—beset by newly emerging threats from every direction. In the east, Daenerys Targaryen, the last scion of House Targaryen, rules with her three dragons as queen of a city built on dust and death. But Daenerys has thousands of enemies, and many have set out to find her. As they gather, one young man embarks upon his own quest for the queen, with an entirely different goal in mind. Fleeing from Westeros with a price on his head, Tyrion Lannister, too, is making his way to Daenerys.But his newest allies in this quest are not the rag - tag band they seem, and at their heart lies one who could undo Daenerys’s claim to Westeros forever." });

            context.Books.Add(new Book { PDate = new System.DateTime(1996, 4, 16), ASIN = "B000FC1ICM", BookID = 42, AuthorID = 20, CoverUrl = "https://prodimage.images-bn.com/pimages/9780679879244_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" }, new Genre { GenreID = 2, GenreTitle = "Fantasy" }, new Genre { GenreID = 3, GenreTitle = "Young Adult" } }, Price = (decimal)9.99, BookName = "The Golden Compass", Publisher = "Random House", Stock = 50, Synopsis = "Here lives an orphaned ward named Lyra Belacqua, whose carefree life among the scholars at Oxford's Jordan College is shattered by the arrival of two powerful visitors. First, her fearsome uncle, Lord Asriel, appears with evidence of mystery and danger in the far North, including photographs of a mysterious celestial phenomenon called Dust and the dim outline of a city suspended in the Aurora Borealis that he suspects is part of an alternate universe. He leaves Lyra in the care of Mrs. Coulter, an enigmatic scholar and explorer who offers to give Lyra the attention her uncle has long refused her. In this multilayered narrative, however, nothing is as it seems. Lyra sets out for the top of the world in search of her kidnapped playmate, Roger, bearing a rare truth-telling instrument, the alethiometer. All around her children are disappearing—victims of so-called 'Gobblers'—and being used as subjects in terrible experiments that separate humans from their daemons, creatures that reflect each person's inner being. And somehow, both Lord Asriel and Mrs. Coulter are involved." });
            context.Books.Add(new Book { PDate = new System.DateTime(1996, 7, 22), ASIN = "B000FC1KJS", BookID = 43, AuthorID = 20, CoverUrl = "https://prodimage.images-bn.com/pimages/9780375823466_p0_v4_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" }, new Genre { GenreID = 2, GenreTitle = "Fantasy" }, new Genre { GenreID = 3, GenreTitle = "Young Adult" } }, Price = (decimal)9.99, BookName = "The Subtle Knife", Publisher = "Random House", Stock = 50, Synopsis = "Lost in a new world, Lyra finds Will—a boy on the run, a murderer—a worthy and welcome ally. For this is a world where soul-eating Specters stalk the streets and witches share the skies with troops of angels. Each is searching—Lyra for the meaning of Dark Matter, Will for his missing father—but what they find instead is a deadly secret, a knife of untold power.And neither Lyra nor Will suspects how tightly their lives, their loves, and their destinies are bound together...until they are split apart." });
            context.Books.Add(new Book { PDate = new System.DateTime(2000, 10, 10), ASIN = "B000FC1GJW", BookID = 44, AuthorID = 20, CoverUrl = "https://prodimage.images-bn.com/pimages/9780679879268_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" }, new Genre { GenreID = 2, GenreTitle = "Romance" },  new Genre { GenreID = 3, GenreTitle = "Young Adult" },  new Genre { GenreID = 3, GenreTitle = "Fantasy" } }, Price = (decimal)23.99, BookName = "The Amber Spyglass", Publisher = "", Stock = 50, Synopsis = "In the astonishing finale to the His Dark Materials trilogy, Lyra and Will are in unspeakable danger. With help from Iorek Byrnison the armored bear and two tiny Gallivespian spies, they must journey to a dank and gray-lit world where no living soul has ever gone. All the while, Dr. Mary Malone builds a magnificent Amber Spyglass. An assassin hunts her down, and Lord Asriel, with a troop of shining angels, fights his mighty rebellion, in a battle of strange allies—and shocking sacrifice. As war rages and Dust drains from the sky, the fate of the living—and the dead—finally comes to depend on two children and the simple truth of one simple story." });

            context.Books.Add(new Book { PDate = new System.DateTime(2004, 5, 1), ASIN = "B00I1W23IG", BookID = 45, AuthorID = 22, CoverUrl = "https://prodimage.images-bn.com/pimages/9781847241696_p0_v2_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Horror" },  new Genre { GenreID = 3, GenreTitle = "Romance" } }, Price = (decimal)15.99, BookName = "Let the Right One In", Publisher = "Quercus", Stock = 50, Synopsis = "It is autumn 1981 when the inconceivable comes to Blackeberg, a suburb in Sweden. The body of a teenage boy is found, emptied of blood, the murder rumored to be part of a ritual killing. Twelve-year-old Oskar is personally hoping that revenge has come at long last—revenge for the bullying he endures at school, day after day. But the murder is not the most important thing on his mind.A new girl has moved in next door—a girl who has never seen a Rubik’s Cube before, but who can solve it at once.There is something wrong with her, though, something odd. And she only comes out at night...." });
            context.Books.Add(new Book { PDate = new System.DateTime(2006, 9, 27), ASIN = "B003P8PLI0", BookID = 46, AuthorID = 22, CoverUrl = "https://prodimage.images-bn.com/pimages/9780312605254_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Horror" } }, Price = (decimal)16.99, BookName = "Handling the Undead", Publisher = "St. Martin's Press", Stock = 50, Synopsis = "Something very peculiar is happening in Stockholm. There's a heatwave on and people cannot turn their lights out or switch their appliances off. Then the terrible news breaks. In the city morgue, the dead are waking up..." });

            context.Books.Add(new Book { PDate = new System.DateTime(2004, 7, 27), ASIN = "B000FC1UR0", BookID = 47, AuthorID = 23, CoverUrl = "https://prodimage.images-bn.com/pimages/9780743262538_p0_v1_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Fantasy" }, new Genre { GenreID = 2, GenreTitle = "Horror" } }, Price = (decimal)25.99, BookName = "Vamped", Publisher = "Gallery Books", Stock = 50, Synopsis = "Martin Kowalski is an eighty-year-old man stuck in a twenty-year-old body. He works the graveyard shift. He has a poster of Bela Lugosi on his wall and a box of uneaten Count Chocula in his pantry. He drinks stem-cell-derived blood from cleverly packaged and marketed juice boxes. He is, in short, a vampire. But since his wildly successful scheme to turn as many mortals as possible into vampires -- 'vamp' them rather than kill them -- resulted in a new immortal majority, Marty finds little of interest to fill his countless days. When Marty decides to end his endless life of soul-crushing ennui -- call it vampire affluenza -- a three-foot blond obstacle is thrown in his path: Isuzu Trooper Cassidy, a refugee from a human hunting preserve. At first he thinks 'midnight snack', but before the sun comes up, Isuzu is the one snacking on his prized cereal collection as she charms him into staying undead long enough to raise her in a world rife with danger and almost entirely populated by vampires yearning for the taste of real human blood." });
            context.Books.Add(new Book { PDate = new System.DateTime(2017, 5, 2), ASIN = "B01N590V3K", BookID = 48, AuthorID = 24, CoverUrl = "https://prodimage.images-bn.com/pimages/9780735211209_p0_v3_s192x300.jpg", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Thriller" }, new Genre { GenreID = 2, GenreTitle = "Psychology" }, new Genre { GenreID = 3, GenreTitle = "Mystery" } }, Price = (decimal)25.99, BookName = "Into the Water", Publisher = "Riverhead Books", Stock = 50, Synopsis = "A single mother turns up dead at the bottom of the river that runs through town. Earlier in the summer, a vulnerable teenage girl met the same fate. They are not the first women lost to these dark waters, but their deaths disturb the river and its history, dredging up secrets long submerged. Left behind is a lonely fifteen - year - old girl.Parentless and friendless, she now finds herself in the care of her mother's sister, a fearful stranger who has been dragged back to the place she deliberately ran from—a place to which she vowed she'd never return." });
            //context.Books.Add(new Book { PDate = new System.DateTime(, , ), ASIN = "", BookID = 44, AuthorID = 20, CoverUrl = "", Genre = new List<Genre> { new Genre { GenreID = 1, GenreTitle = "Science Fiction" }, new Genre { GenreID = 2, GenreTitle = "Romance" },  new Genre { GenreID = 3, GenreTitle = "Young Adult" },  new Genre { GenreID = 3, GenreTitle = "Romance" } }, Price = (decimal)25.99, BookName = "", Publisher = "", Stock = 50, Synopsis = "" });


            //context.Users.Add(new Account { UID = 1, FirstName = "Adam", LastName = "Levy", Email = "alevy030@fiu.edu", Username = "alevy030", PassWord = "alevy030", ConfirmPassword = "alevy030" });
            //context.Users.Add(new Account { UID = 2, FirstName = "Juan", LastName = "Hernandez", Email = "juaneh5@gmail.com", Username = "juaneh5", PassWord = "juaneh5", ConfirmPassword = "juaneh5" });
            //context.Users.Add(new Account { UID = 3, FirstName = "Brandon", LastName = "Cajigas", Email = "BrandonCaj@gmail.com", Username = "BrandonCaj", PassWord = "BrandonCaj", ConfirmPassword = "BrandonCaj" });
            //context.Users.Add(new Account { UID = 4, FirstName = "Alex", LastName = "Dubuisson", Email = "adubu002@fiu.edu", Username = "adubu002", PassWord = "adubu002", ConfirmPassword = "adubu002" });

            //context.Avatars.Add(new Avatar { UID = 1, AVATARID = 1, ImageUrl = "~/Content/Images/avatar01.png" });

            //context.Addresses.Add(new Address { UID = 4, AID = 1, StreetAddress = "13401 NE 8th Street", AddressTwo = "", City = "Miami", Country = "United States", Postal = "33186", State_Province = "Florida" });
            base.Seed(context);
        }
    }
}